package io.github.bineq.medalog;

import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Second-pass ANTLR4 visitor that generates compiled Souffle Datalog output.
 *
 * <p>Transformations performed:
 * <ul>
 *   <li>{@code .decl} predicates receive an {@code id symbol} first slot (unless already present).</li>
 *   <li>Facts receive a compiler-assigned or {@code @id}-specified identifier as first argument.</li>
 *   <li>Rule heads and bodies are rewritten to carry provenance IDs via the pluggable
 *       {@link AggregationStrategy}.</li>
 *   <li>{@code _module} membership facts are generated for rules/modules inside modules.</li>
 *   <li>{@code _assertedAnnotation} facts are generated for asserted (non-id) annotations.</li>
 *   <li>An annotation-inheritance rule is emitted so that annotations propagate from enclosing
 *       modules to their contents unless overridden.</li>
 * </ul>
 */
public class CodeGenerator extends MeDaLogBaseVisitor<String> {

    private static final Logger LOG = LoggerFactory.getLogger(CodeGenerator.class);

    private final SymbolTable symbolTable;
    private final AggregationStrategy aggregation;
    private final String inputText;

    private final StringBuilder output = new StringBuilder();

    /** Stack of active module IDs while visiting nested modules (innermost on top). */
    private final Deque<String> moduleStack = new ArrayDeque<>();

    /** All IDs registered so far; used for duplicate-ID detection. */
    private final Set<String> allocatedIds = new HashSet<>();

    /** Accumulated _module facts, emitted at the end of the program. */
    private final List<String> moduleFacts = new ArrayList<>();

    /** Accumulated _assertedAnnotation facts, emitted at the end of the program. */
    private final List<String> annotationFacts = new ArrayList<>();

    /** Counter for fresh body-id variable names, reset for each rule. */
    private int bodyIdVarCounter;

    public CodeGenerator(SymbolTable symbolTable, AggregationStrategy aggregation, String inputText) {
        this.symbolTable = symbolTable;
        this.aggregation = aggregation;
        this.inputText = inputText;
    }

    /** Returns the complete generated Souffle source. */
    public String getOutput() {
        return output.toString();
    }

    // ==============================
    // Program
    // ==============================

    @Override
    public String visitProgram(MeDaLogParser.ProgramContext ctx) {
        output.append("// Generated by MeDaLog compiler\n\n");
        emitBuiltinDeclarations();

        for (MeDaLogParser.StatementContext stmt : ctx.statement()) {
            visit(stmt);
        }

        if (!moduleFacts.isEmpty()) {
            output.append("\n// Module membership facts\n");
            moduleFacts.forEach(f -> output.append(f).append("\n"));
        }

        if (!annotationFacts.isEmpty()) {
            output.append("\n// Asserted annotation facts\n");
            annotationFacts.forEach(f -> output.append(f).append("\n"));
        }

        output.append("\n// Annotation inheritance\n");
        output.append("_annotationKeyAsserted(id, key) :- _assertedAnnotation(id, key, _).\n");
        output.append("_annotation(id, key, val) :- _assertedAnnotation(id, key, val).\n");
        output.append("_annotation(id, key, val) :-\n");
        output.append("    _module(id, modId),\n");
        output.append("    _annotation(modId, key, val),\n");
        output.append("    !_annotationKeyAsserted(id, key).\n");

        return null;
    }

    private void emitBuiltinDeclarations() {
        output.append(".decl _module(ruleOrModuleId: symbol, moduleId: symbol)\n");
        output.append(".decl _assertedAnnotation"
                + "(id: symbol, annotation_name: symbol, annotation_value: symbol)\n");
        output.append(".decl _annotationKeyAsserted(id: symbol, annotation_name: symbol)\n");
        output.append(".decl _annotation"
                + "(id: symbol, annotation_name: symbol, annotation_value: symbol)\n\n");
    }

    // ==============================
    // Statement
    // ==============================

    @Override
    public String visitStatement(MeDaLogParser.StatementContext ctx) {
        if (ctx.moduleDecl() != null) {
            return visit(ctx.moduleDecl());
        }
        return visit(ctx.annotatedStatement());
    }

    // ==============================
    // Module declaration
    // ==============================

    @Override
    public String visitModuleDecl(MeDaLogParser.ModuleDeclContext ctx) {
        List<Annotation> annotations = parseAnnotations(ctx.annotation());
        String moduleId = ctx.IDENTIFIER().getText();
        int line = ctx.getStart().getLine();

        // The module name is semantically @id
        registerNewId(moduleId, line);

        // This module is a member of its parent module (if any)
        if (!moduleStack.isEmpty()) {
            moduleFacts.add("_module(\"" + esc(moduleId) + "\", \""
                    + esc(moduleStack.peek()) + "\").");
        }

        // Emit asserted annotations for the module
        emitAnnotationFacts(moduleId, annotations);

        moduleStack.push(moduleId);
        LOG.info("Entering module '{}' at line {}.", moduleId, line);

        output.append("\n// --- module ").append(moduleId).append(" ---\n");
        for (MeDaLogParser.StatementContext stmt : ctx.statement()) {
            visit(stmt);
        }

        moduleStack.pop();
        return null;
    }

    // ==============================
    // Annotated statement dispatch
    // ==============================

    @Override
    public String visitAnnotatedStatement(MeDaLogParser.AnnotatedStatementContext ctx) {
        List<Annotation> annotations = parseAnnotations(ctx.annotation());
        MeDaLogParser.SouffleItemContext item = ctx.souffleItem();

        if (item.predDeclaration() != null) {
            return visitPredDeclaration(item.predDeclaration());
        } else if (item.typeDeclaration() != null) {
            return visitTypeDeclaration(item.typeDeclaration());
        } else if (item.souffleDirective() != null) {
            return visitSouffleDirective(item.souffleDirective());
        } else if (item.rule_() != null) {
            return compileMeDaLogRule(item.rule_(), annotations);
        } else if (item.fact() != null) {
            return compileMeDaLogFact(item.fact(), annotations);
        }
        return null;
    }

    // ==============================
    // Predicate declaration
    // ==============================

    @Override
    public String visitPredDeclaration(MeDaLogParser.PredDeclarationContext ctx) {
        String name = ctx.IDENTIFIER().getText();
        PredicateInfo info = symbolTable.getPredicate(name);

        output.append(".decl ").append(name).append("(");

        if (info != null && !info.isAlreadyHasIdSlot()) {
            output.append("id: symbol");
            if (ctx.paramList() != null && !ctx.paramList().param().isEmpty()) {
                output.append(", ");
            }
        }

        if (ctx.paramList() != null) {
            output.append(rebuildParamList(ctx.paramList()));
        }
        output.append(")");

        for (MeDaLogParser.DeclQualifierContext q : ctx.declQualifier()) {
            output.append(" ").append(q.getText());
        }
        output.append("\n");
        return null;
    }

    private String rebuildParamList(MeDaLogParser.ParamListContext ctx) {
        List<String> parts = new ArrayList<>();
        for (MeDaLogParser.ParamContext p : ctx.param()) {
            parts.add(p.IDENTIFIER().getText() + ": " + p.souffleType().getText());
        }
        return String.join(", ", parts);
    }

    // ==============================
    // Pass-through items
    // ==============================

    @Override
    public String visitTypeDeclaration(MeDaLogParser.TypeDeclarationContext ctx) {
        output.append(originalText(ctx)).append("\n");
        return null;
    }

    @Override
    public String visitSouffleDirective(MeDaLogParser.SouffleDirectiveContext ctx) {
        output.append(originalText(ctx)).append("\n");
        return null;
    }

    // ==============================
    // Fact compilation
    // ==============================

    private String compileMeDaLogFact(MeDaLogParser.FactContext ctx,
                                      List<Annotation> annotations) {
        String predName = ctx.atom().IDENTIFIER().getText();
        int line = ctx.getStart().getLine();

        if (!symbolTable.isDeclared(predName)) {
            output.append(originalText(ctx)).append("\n");
            return null;
        }

        String factId = resolveId(annotations, line);
        registerNewId(factId, line);

        if (!moduleStack.isEmpty()) {
            moduleFacts.add("_module(\"" + esc(factId) + "\", \""
                    + esc(moduleStack.peek()) + "\").");
        }
        emitAnnotationFacts(factId, annotations);

        PredicateInfo info = symbolTable.getPredicate(predName);
        output.append(predName).append("(\"").append(esc(factId)).append("\"");
        if (ctx.atom().argList() != null && !ctx.atom().argList().arg().isEmpty()) {
            output.append(", ").append(rebuildArgList(ctx.atom().argList()));
        }
        output.append(").\n");
        return null;
    }

    // ==============================
    // Rule compilation
    // ==============================

    private String compileMeDaLogRule(MeDaLogParser.Rule_Context ctx,
                                      List<Annotation> annotations) {
        String predName = ctx.atom().IDENTIFIER().getText();
        int line = ctx.getStart().getLine();

        if (!symbolTable.isDeclared(predName)) {
            output.append(originalText(ctx)).append("\n");
            return null;
        }

        String ruleId = resolveId(annotations, line);
        registerNewId(ruleId, line);

        if (!moduleStack.isEmpty()) {
            moduleFacts.add("_module(\"" + esc(ruleId) + "\", \""
                    + esc(moduleStack.peek()) + "\").");
        }
        emitAnnotationFacts(ruleId, annotations);

        // Transform body: inject id variables into declared predicate atoms
        bodyIdVarCounter = 0;
        List<String> bodyIdVars = new ArrayList<>();
        String transformedBody = rebuildBody(ctx.body(), bodyIdVars);

        // Compute head ID expression from rule ID + collected body-atom id vars
        String ruleIdExpr = "\"" + esc(ruleId) + "\"";
        String headIdExpr = aggregation.generateId(ruleIdExpr, bodyIdVars);

        // Emit transformed rule
        output.append(predName).append("(").append(headIdExpr);
        if (ctx.atom().argList() != null && !ctx.atom().argList().arg().isEmpty()) {
            output.append(", ").append(rebuildArgList(ctx.atom().argList()));
        }
        output.append(") :-\n    ").append(transformedBody).append(".\n");
        return null;
    }

    // ==============================
    // Body transformation
    // ==============================

    private String rebuildBody(MeDaLogParser.BodyContext ctx, List<String> bodyIdVars) {
        List<String> parts = new ArrayList<>();
        for (MeDaLogParser.BodyElementContext elem : ctx.bodyElement()) {
            parts.add(rebuildBodyElement(elem, bodyIdVars));
        }
        return String.join(",\n    ", parts);
    }

    private String rebuildBodyElement(MeDaLogParser.BodyElementContext ctx,
                                      List<String> bodyIdVars) {
        if (ctx.comparison() != null) {
            return originalText(ctx.comparison());
        }
        if (ctx.NEG() != null) {
            // Negated atom: add wildcard for id slot if predicate is declared
            String neg = ctx.NEG().getText();
            MeDaLogParser.AtomContext ac = ctx.atom();
            String name = ac.IDENTIFIER().getText();
            if (symbolTable.isDeclared(name) && !symbolTable.getPredicate(name).isAlreadyHasIdSlot()) {
                StringBuilder sb = new StringBuilder(neg).append(name).append("(_");
                if (ac.argList() != null && !ac.argList().arg().isEmpty()) {
                    sb.append(", ").append(rebuildArgList(ac.argList()));
                }
                return sb.append(")").toString();
            }
            return neg + originalText(ac);
        }
        if (ctx.atom() != null) {
            return rebuildPositiveAtom(ctx.atom(), bodyIdVars);
        }
        if (ctx.body() != null) {
            // Parenthesized sub-body
            String inner = rebuildBody(ctx.body(), bodyIdVars);
            return "(" + inner + ")";
        }
        if (ctx.aggregateExpr() != null) {
            return originalText(ctx.aggregateExpr());
        }
        return originalText(ctx);
    }

    private String rebuildPositiveAtom(MeDaLogParser.AtomContext ctx,
                                       List<String> bodyIdVars) {
        String name = ctx.IDENTIFIER().getText();
        if (symbolTable.isDeclared(name) && !symbolTable.getPredicate(name).isAlreadyHasIdSlot()) {
            String idVar = "_id" + (++bodyIdVarCounter);
            bodyIdVars.add(idVar);
            StringBuilder sb = new StringBuilder(name).append("(").append(idVar);
            if (ctx.argList() != null && !ctx.argList().arg().isEmpty()) {
                sb.append(", ").append(rebuildArgList(ctx.argList()));
            }
            return sb.append(")").toString();
        }
        return originalText(ctx);
    }

    private String rebuildArgList(MeDaLogParser.ArgListContext ctx) {
        List<String> parts = new ArrayList<>();
        for (MeDaLogParser.ArgContext a : ctx.arg()) {
            parts.add(originalText(a));
        }
        return String.join(", ", parts);
    }

    // ==============================
    // Annotation processing
    // ==============================

    /**
     * Parses annotation contexts, validating for conflicts and emitting warnings
     * for equivalent-but-unequal keys.
     */
    private List<Annotation> parseAnnotations(List<MeDaLogParser.AnnotationContext> ctxList) {
        Map<String, Annotation> byRawKey = new LinkedHashMap<>();
        List<Annotation> result = new ArrayList<>();

        for (MeDaLogParser.AnnotationContext ctx : ctxList) {
            String rawKey = buildAnnotationKey(ctx.annotationKey());
            AnnotationValue value = parseAnnotationValue(ctx.annotationValue());
            int line = ctx.getStart().getLine();
            Annotation ann = new Annotation(rawKey, value, line);

            // Warning: key is @id-equivalent but not literally "id"
            if (!rawKey.equals("id") && rawKey.trim().toLowerCase().equals("id")) {
                LOG.warn("Line {}: annotation key '{}' is equivalent to 'id'; "
                        + "treating as @id.", line, rawKey);
            }

            // Warning: different spellings of keys that normalise to the same value
            String normKey = ann.normalisedKey();
            for (Map.Entry<String, Annotation> e : byRawKey.entrySet()) {
                if (!e.getKey().equals(rawKey) && e.getValue().normalisedKey().equals(normKey)) {
                    LOG.warn("Line {}: annotation key '{}' is equivalent to earlier key '{}'; "
                            + "both applied.", line, rawKey, e.getKey());
                }
            }

            // Error: same key, different value for the same rule/module
            if (byRawKey.containsKey(rawKey)) {
                Annotation prev = byRawKey.get(rawKey);
                if (!prev.value().toRawString().equals(value.toRawString())) {
                    throw new CompilerException(
                            "Conflicting annotations for key '" + rawKey + "': '"
                                    + prev.value().toRawString() + "' vs '"
                                    + value.toRawString() + "'",
                            line);
                }
                // Duplicate with same value: silently ignore the second
            } else {
                byRawKey.put(rawKey, ann);
                result.add(ann);
            }
        }
        return result;
    }

    private String buildAnnotationKey(MeDaLogParser.AnnotationKeyContext ctx) {
        List<String> parts = new ArrayList<>();
        for (TerminalNode id : ctx.IDENTIFIER()) {
            parts.add(id.getText());
        }
        return String.join("-", parts);
    }

    private AnnotationValue parseAnnotationValue(MeDaLogParser.AnnotationValueContext ctx) {
        if (ctx.stringValue() != null) {
            String raw = ctx.stringValue().STRING().getText();
            String content = raw.substring(1, raw.length() - 1)
                    .replace("\\\"", "\"").replace("\\\\", "\\");
            return new AnnotationValue.StringVal(content);
        }
        if (ctx.numberValue() != null) {
            String sign = ctx.numberValue().MINUS() != null ? "-" : "";
            String digits = ctx.numberValue().INTEGER() != null
                    ? ctx.numberValue().INTEGER().getText()
                    : ctx.numberValue().FLOAT_LIT().getText();
            return new AnnotationValue.NumberVal(sign + digits);
        }
        if (ctx.booleanValue() != null) {
            return new AnnotationValue.BooleanVal("true".equals(ctx.booleanValue().BOOLEAN().getText()));
        }
        if (ctx.timestampValue() != null) {
            return new AnnotationValue.TimestampVal(ctx.timestampValue().getText());
        }
        if (ctx.jsonObject() != null) {
            return new AnnotationValue.JsonVal(originalText(ctx.jsonObject()));
        }
        if (ctx.jsonArray() != null) {
            return new AnnotationValue.JsonVal(originalText(ctx.jsonArray()));
        }
        throw new CompilerException("Unrecognised annotation value",
                ctx.getStart().getLine());
    }

    /**
     * Returns the @id value from the annotation list.
     * If absent, generates a fresh ID from the symbol table.
     * Note: @id is NOT inherited from enclosing modules.
     */
    private String resolveId(List<Annotation> annotations, int line) {
        for (Annotation a : annotations) {
            if (a.normalisedKey().equals("id")) {
                if (!a.key().equals("id")) {
                    LOG.warn("Line {}: annotation key '{}' is equivalent to 'id'; treating as @id.",
                            line, a.key());
                }
                return a.value().toRawString();
            }
        }
        // No @id: check if enclosing module provides one? Spec says @id cannot be inherited.
        // Generate a fresh ID.
        return symbolTable.nextFactId();
    }

    /** Registers an ID, throwing {@link CompilerException} if already allocated. */
    private void registerNewId(String id, int line) {
        if (!allocatedIds.add(id)) {
            throw new CompilerException("Duplicate @id value: '" + id + "'", line);
        }
    }

    /** Emits _assertedAnnotation facts for all non-@id annotations. */
    private void emitAnnotationFacts(String id, List<Annotation> annotations) {
        for (Annotation ann : annotations) {
            if (!ann.isId()) {
                annotationFacts.add(
                        "_assertedAnnotation(\""
                                + esc(id) + "\", \""
                                + esc(ann.key()) + "\", \""
                                + esc(ann.value().toRawString()) + "\").");
            }
        }
    }

    // ==============================
    // Text reconstruction
    // ==============================

    /**
     * Returns the original source text for a parse-tree node by slicing the input
     * string using character offsets from the start/stop tokens.
     */
    private String originalText(ParserRuleContext ctx) {
        if (ctx == null) return "";
        if (ctx.stop == null) return ctx.getText();
        int start = ctx.start.getStartIndex();
        int stop = ctx.stop.getStopIndex();
        if (start < 0 || stop < start || stop >= inputText.length()) {
            return ctx.getText();
        }
        return inputText.substring(start, stop + 1);
    }

    // ==============================
    // Utility
    // ==============================

    private static String esc(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
