// compiler generates F1 as first auto-assigned fact id
.decl _module(ruleOrModuleId symbol, moduleId symbol)
.decl _assertedAnnotation(id symbol, annotation_name symbol, annotation_value symbol)
.decl _annotationKeyAsserted(id symbol, annotation_name symbol)
.decl _annotation(id symbol, annotation_name symbol, annotation_value symbol)

.decl parent(id: symbol, x: symbol, y: symbol)
parent("F1", "Tim", "Tom").

_annotationKeyAsserted(id, key) :- _assertedAnnotation(id, key, _).
_annotation(id, key, val) :- _assertedAnnotation(id, key, val).
_annotation(id, key, val) :-
    _module(id, modId),
    _annotation(modId, key, val),
    !_annotationKeyAsserted(id, key).
