// two annotations on a module produce two _assertedAnnotation facts
.decl _module(ruleOrModuleId: symbol, moduleId: symbol)
.decl _assertedAnnotation(id: symbol, annotation_name: symbol, annotation_value: symbol)
.decl _annotationKeyAsserted(id: symbol, annotation_name: symbol)
.decl _annotation(id: symbol, annotation_name: symbol, annotation_value: symbol)

_assertedAnnotation("mymod", "author", "Team").
_assertedAnnotation("mymod", "version", "2").

_annotationKeyAsserted(id, key) :- _assertedAnnotation(id, key, _).
_annotation(id, key, val) :- _assertedAnnotation(id, key, val).
_annotation(id, key, val) :-
    _module(id, modId),
    _annotation(modId, key, val),
    !_annotationKeyAsserted(id, key).
