// rule with @id: head gets cat-aggregated id from rule id + body atom ids
.decl _module(ruleOrModuleId: symbol, moduleId: symbol)
.decl _assertedAnnotation(id: symbol, annotation_name: symbol, annotation_value: symbol)
.decl _annotationKeyAsserted(id: symbol, annotation_name: symbol)
.decl _annotation(id: symbol, annotation_name: symbol, annotation_value: symbol)

.decl grandparent(id: symbol, gp: symbol, gc: symbol)
.decl parent(id: symbol, p: symbol, c: symbol)
grandparent(cat("gprule", cat("[", cat(_id1, cat(",", cat(_id2, "]"))))), x, y) :-
    parent(_id1, x, z),
    parent(_id2, z, y).

_annotationKeyAsserted(id, key) :- _assertedAnnotation(id, key, _).
_annotation(id, key, val) :- _assertedAnnotation(id, key, val).
_annotation(id, key, val) :-
    _module(id, modId),
    _annotation(modId, key, val),
    !_annotationKeyAsserted(id, key).
