// negated body atom gets wildcard _ for the id slot
.decl _module(ruleOrModuleId: symbol, moduleId: symbol)
.decl _assertedAnnotation(id: symbol, annotation_name: symbol, annotation_value: symbol)
.decl _annotationKeyAsserted(id: symbol, annotation_name: symbol)
.decl _annotation(id: symbol, annotation_name: symbol, annotation_value: symbol)

.decl active(id: symbol, x: symbol)
.decl removed(id: symbol, x: symbol)
.decl result(id: symbol, x: symbol)
result(cat("r1", cat("[", cat(_id1, "]"))), x) :-
    active(_id1, x),
    !removed(_, x).

_annotationKeyAsserted(id, key) :- _assertedAnnotation(id, key, _).
_annotation(id, key, val) :- _assertedAnnotation(id, key, val).
_annotation(id, key, val) :-
    _module(id, modId),
    _annotation(modId, key, val),
    !_annotationKeyAsserted(id, key).
