// Source: tests/evaluation/empty_relations/empty_relations.dl
// Tests empty base relations and component instantiation with empty body rules

// Bug #1 -- an empty relation due to the absence of facts
//      this was resulting in a seg-fault

.decl A(x:number)
.decl B(x:number)
B(1) :- A(x).



// Bug #2 - an empty relation as the result of a component
//      this was resulting in a seg-fault

.decl C(x:number)
.output C()

.comp X {
    .decl D(x:number)
    D(1) :- C(x).
}

.init x=X
